### ISSUE TITLE
Feature request: default value for option

### ISSUE THREAD

**Issue by Antonboom** [kazhuravlev/options-gen#13]
Like in [envconfig](https://github.com/kelseyhightower/envconfig):
```go
type Options struct {
    pingPeriod time.Duration `default="3s" validate:"min=100ms,max=30s"`
}
```

**Comment by kazhuravlev** [comment]
Default values are suitable only for very-simple field types. The default tag will not be enough for fields like nested structs (http.Client), interfaces, or even a slice of something.


Maybe we need to add functions (bounded or not), which will be found and called by options-gen.

I have no idea how to implement this nicely.
