### ISSUE TITLE
Feature request: support own validator using

### ISSUE THREAD

**Issue by Antonboom** [kazhuravlev/options-gen#15]
A situation is possible when the project uses a global validator in which custom functions, tags, etc. are registered.
At the moment there is no way to override the validator for options and use your existing one.

**Comment by kazhuravlev** [comment]
At this moment, I am not sure that this is a popular case. And when we try to add a custom validator, we should think about:
- Is this overriding for specific Options struct or the whole project? Like by calling the `optionsgen.SetValidator(myValidator)` in the `main.go`; or something like `func (Options)Validator() *validator.Validator`.
- It needs to use a custom validator (not go-playground/validator)? How is it can work?

**Comment by Antonboom** [comment]
> It needs to use a custom validator (not go-playground/validator)?
No, I think it's redundant and unnecessary.

> Is this overriding for specific Options struct or the whole project?
both :) I think interface is a cool variant

```go
package validator

import (
	"github.com/go-playground/validator/v10"
)

var Validator = validator.New()

func init() {
    // Custom functions registration, etc.
    // ...
}

```

```go
package service

import "internal/validator"

type Options struct {
    // ...
}

func (Options) Validator() *validator.Validate {
    return validator.Validator
}
```

```go
package service

var _validator461e464ebed9 = goplvalidator.New()

func getOptsValidatorOrDefault(opts any) *goplvalidator.Validate {
	if v, ok := opts.(interface {
		Validator() *goplvalidator.Validate
	}); ok {
		return v.Validator()
	}
	return _validator461e464ebed9
}
```
