### ISSUE TITLE
Feature request: possible improvements: zero-dependency and goroutines issue

### ISSUE THREAD

**Issue by Antonboom** [kazhuravlev/options-gen#24]
I think, it's cool when the tool is self-sufficient both in itself and the code that it generates is self-sufficient.
Also it's cool when dubious things are not dictated, but they can be configured.

Based on this, I propose:

- [ ] Use external libraries to a minimum
  - [ ] **github.com/go-playground/validator/v10** – Figure out how to customize this stuff (related to https://github.com/kazhuravlev/options-gen/issues/15)
  - [x] **github.com/hashicorp/go-multierror** – Replace with custom implementation.
  - [x] **github.com/pkg/errors** – Remove.
- [x] Validation through goroutines is doubtful – this is an obvious overhead, complicating the code and not giving much benefit.

I'm not the only one who [noticed this](https://t.me/goinpractice/3323). I propose either removing it or putting it in the configuration, and by default validate with a simple synchronous code.

**Comment by kazhuravlev** [comment]
That is a perfect point. I am already started to fix problems. Previously, I was not sure that it was a problem for users. But now - I am sure and will fix these points faster. Thanks for motivation ❤️

**Comment by kazhuravlev** [comment]
@Antonboom The point about the validator is duplicated by #15. so I closed this ticket as completed (other issues already in master).
