### ISSUE TITLE
Add the warning for Options fields that published

### ISSUE THREAD

**Issue by kazhuravlev** [kazhuravlev/options-gen#27]
options-gen should print the warning about field `S3Endpoint` (because ayone can change this option without constructor) in that case:

```
type Options struct {
  S3Endpoint string `option:"mandatory"`
}
```

- [x] Print warning about public field in `Options` struct.
- [ ] Allow to disable warning by specify an argument like `//go:generate options-gen .... --mute-warnings`. By default it is enabled.
- [ ] Previous flag should disable warnings about deprecated option flags (`required`, `not-empty`).

**Comment by Antonboom** [comment]
Maybe by default to issue not a warning, but an error?
Thus to work like a linter.

**Comment by kazhuravlev** [comment]
@Antonboom It sounds interesting, but I will create a separate issue for this idea. I will add it in the next major version. This will break compatibility right now.
