### ISSUE TITLE
Unexpected behaviour: validating optional options

### ISSUE THREAD

**Issue by kazhuravlev** [kazhuravlev/options-gen#36]
```go
//go:generate options-gen -from-struct=Options
type Options struct {
	option string `validate:"required"`
}
```

```go
if err := NewOptions().Validate(); err != nil {
	panic(err)
}
```

**Comment by Antonboom** [comment]
It was expected behaviour for me :)

I fixed it with `omitempty`, for example, `validate:"omitempty,hexadecimal"`.

**Comment by kazhuravlev** [comment]
Maybe we should automatically add omitempty, when option is not mandatory?

I don't known how it will works with required tag.

**Comment by kazhuravlev** [comment]
There is no obvious solution - I'm closing this issue.
