### ISSUE TITLE
muti generated will naming conflicts

### ISSUE THREAD

**Issue by ercJuL** [kazhuravlev/options-gen#49]
Multiple options-gen in the same pkg, how to resolve naming conflicts
```golang
type A struct {s string}
type B struct {s string}
```

The above code will generate the same `WithS(opt sting){...}`

so, how to resolve this.

i add struct name to func like `WithAS(opt string)` `WithBS(opt string)`

but this naming method will cause the function name to be too long

![image](https://github.com/kazhuravlev/options-gen/assets/25130776/8b14fbc3-76b4-4131-ab18-cbbea04ac7a1)

**Comment by kazhuravlev** [comment]
Hi, @ercJuL. Sorry for late response. Check the latest version of options-gen, PR #50 and examples directory [here](https://github.com/kazhuravlev/options-gen/blob/0889cef0d87a02ca7c3ae201690998c5c926f548/examples/go-generate-2options-1pkg/options.go#L3). 

I suppose this will solve your problem.

**Comment by kazhuravlev** [comment]
I close the issue. If this solution is not enough - just reopen the issue.
