### ISSUE TITLE
Getting information about set flags

### ISSUE THREAD

**Issue by kazhuravlev** [kazhuravlev/options-gen#53]
Idea: Sometimes we need to know - which fields are set. But often - we don't. So we need an option to generate additional helpers that allow us to check it.

- [x] Add a new boolean flag to `options-gen`, such as `-with-isset`.
- [x] When this flag is specified, generate a `func (o Options) IsSet(field optionsField) bool`.
- [x] When this flag is specified, generate a `type optionsField int` and constants for all fields (please consider the appropriate constant prefixes for each field).
- [x] Store the set/not set status somewhere to be used in the `With*` functions and the `IsSet` function.

Links:
- [Pull Request](https://github.com/kazhuravlev/options-gen/pull/52)
- [Comment](https://github.com/kazhuravlev/options-gen/pull/52#issuecomment-2127959492)

**Comment by kazhuravlev** [comment]
PR is here https://github.com/kazhuravlev/options-gen/pull/55

**Comment by ccoVeille** [comment]
Completed or not planned?

**Comment by kazhuravlev** [comment]
@ccoVeille completed in #55, merged into master and tagged. `v0.33.0`

**Comment by ccoVeille** [comment]
Thanks, my bad. I saw you closed 52 for inactivity and thought you closed 53 because of it.
