### ISSUE TITLE
errgroup.Group in Validate() is useless?

### ISSUE THREAD

**Issue by Antonboom** [kazhuravlev/options-gen#9]
Hello!

Surely not faster and easier to validate with synchronous code in order?
Were there benchmarks?

```go
func (o *Options) Validate() error {
	g := new(errgroup.Group)

	g.Go(func() error {
		err := _Options_dbValidator(o)

		return errors.Wrap(err, "invalid value for option WithDb")
	})
	return g.Wait()
}
```

**Comment by kazhuravlev** [comment]
Hi! That is useful for the Options struct that has at least two options. In that case, the user can check all errors about all options. Without errgroup user will get an error only for the first error that occurs.

**Comment by Antonboom** [comment]
> Without errgroup user will get an error only for the first error that occurs
But errgroup cancel other routines if at least one failed. And u always receive only first error how u wrote. 🤔 

Did you mess up with https://github.com/uber-go/multierr?
Or with https://github.com/hashicorp/go-multierror/blob/master/group.go?

**Comment by kazhuravlev** [comment]
Yeah, multierr will be a better solution in this case. I'll fix this.
